export enum MediaTypeEnum {
  JPEG = 'image/jpeg',
  GIF = 'image/gif',
  PNG = 'image/png',
  XML = 'text/xml',
  HTML = 'text/html',
  MPEG = 'audio/mpeg',
  OGG = 'audio/ogg',
  ZIP = 'application/zip',
  PDF = 'application/pdf',
  MSWORD = 'application/msword',
  SQL = 'application/sql',
  JSON = 'application/json',
  GRAPHQL = 'application/graphql',
  JAVASCRIP = 'application/javascript',
  NONE = 'none',
}
